### ISSUE TITLE
Hud not showing when using PROTON_USE_WINED3D=1 (opengl)

### ISSUE THREAD

**Issue by mmbossoni** [flightlessmango/MangoHud#1055]
**Describe the bug**
When unsing Wine d3d through PROTON_USE_WINED3D=1 hud is not shown
On the logs I can see:
[2023-06-23 18:48:31.591] [MANGOHUD] [info] [gl_hud.cpp:114] libvulkan is loaded, skipping OPENGL
[2023-06-23 18:48:31.613] [MANGOHUD] [info] [gl_hud.cpp:114] libvulkan is loaded, skipping OPENGL

**List relevant hardware/software information**
Operating System: Arch Linux 
Graphics Platform: Wayland
Graphics Processor: NVIDIA GeForce GTX 1070/PCIe/SSE2
Mangohud: 0.6.9.1.r81.g12567c6-1

**To Reproduce**
Launch some game (usually retro/dx9 games) with PROTON_USE_WINED3D=1

**Expected behavior**
Hud is visible

[steam-2022780.log](https://github.com/flightlessmango/MangoHud/files/11853351/steam-2022780.log)

**Comment by flightlessmango** [comment]
Wined3d requires `mangohud --dlsym %command%`

**Comment by mmbossoni** [comment]
@flightlessmango I wouldn't open the issue if I didn't have tried dlsym
this is the entire line I'm using
PROTON_USE_WINED3D=1 mangohud --dlsym %command%

**Comment by Hasshu** [comment]
I seem to be experiencing the same issue with plain Wine on Fedora Linux 38: when I try to launch the GOG version of *Oblivion* with `--dlsym`, the output claims that "libvulkan is loaded, skipping OPENGL", but MangoHud never appears.

Apparently, DXVK support for D3DX9 in Fedora had to be [disabled](https://bugzilla.redhat.com/show_bug.cgi?id=1980417#c1) due to a [Wine bug](https://bugs.winehq.org/show_bug.cgi?id=45277), hence WineD3D. Could it be that MangoHud gets "confused" by this workaround, and tries to use DXVK anyway?

MangoHud version: 0.6.9-1; GPU: AMD Radeon RX 6650 XT.

**Comment by flightlessmango** [comment]
This should resolved in 602ba78ea376460d09bcbaaa25bcaa020637f21b and 30395ab94716948da2b6628ec12357aff3822427

**Comment by mmbossoni** [comment]
Seems like it is working fine now :)

**Comment by shmerl** [comment]
Can you please make a new tag with this feature? Just got hit by it and I see it's already fixed in master.

Thanks!
