### ISSUE TITLE
Feature: amdgpu support for temp1-3 [PATCH]

### ISSUE THREAD

**Issue by axet** [flightlessmango/MangoHud#1062]
**Describe the bug**

amd video card has multiply temp sensors. By default mangohud only using temp1_input which is not optional. Since this is not a maximum temperature. According to 'lm_sensors' package maximum temperature is 'junction' which is corresponding to 'temp2_input' sensor.

On my video card (RX 6600) temp1_input around 60 when temp2_input about 80.

I suggest add MAX from all 3 temp sensors to show user maxmium temperature on video card, not 1 sensor.

**List relevant hardware/software information**

- debian bookworm
- MangoHud 0.6.8-2
- GPU RX 6600

**Expected behavior**

mangohud show maximum temp. not first sensor values.

**Additional context**

* https://gitlab.com/axet/homebin/-/blob/debian/cdebian-dget.d/bookworm/mangohud/amdgpu_3_temp.patch

**Comment by flightlessmango** [comment]
I'm thinking this and removing `gpu_temp_junction` as well. Could you PR this?

**Comment by siroccal** [comment]
> I'm thinking this and removing `gpu_temp_junction` as well. Could you PR this?

No, you should keep the normal/average die temperature and junction temperature separate. They're not the same thing and they should not be treated the same. It is normal for the junction temperature to go higher than die temperature: https://www.techpowerup.com/258228/110-c-hotspot-temps-expected-and-within-spec-amd-on-rx-5700-series-thermals.
AMD's own performance metric software also shows both temperatures separately: https://www.amd.com/en/support/kb/faq/dh3-038.

**Comment by axet** [comment]
Basically you are saying - I want all three temp but I wont tell you which video card has which temperature limits on every temp sensor. I do not think MangoHud should be treated as system monitor software. Showing maximum temperature is the one way showing minimum information on screen with most important values. Showing all three values, or showing first one, without helping user to understand it's limits - uninformative.

Since I created patch for mango 0.6.8, which only showing first temp sensor. I suggested to show maximum temperature.

Recent dev branch already showing three temps sensors, we do not need to change anything. Me? I would prefer less screen pollution with one maximum temp sensor value.

**Comment by siroccal** [comment]
> I wont tell you which video card has which temperature limits on every temp sensor

Every GPU has different temperature limits and the normal/average die limit is different from the junction (hotspot) temperature limit. Older GPU's often don't even have a junction temperature measurement diode (or memory temperature).

> Showing maximum temperature is the one way showing minimum information on screen with most important values.

If you're interested in seeing the hotspot temperature, then you should just enable `gpu_junction_temp`. But this temperature is not necessarily the most important, since it's safe to go quite high. And people will get scared by high values if only the junction temperature is shown and they don't know it's a junction temperature that is safe to go high.

> Showing all three values, or showing first one, without helping user to understand it's limits - uninformative.

Showing both the normal/average die temperature and the junction temperature is very informative, but takes more space. Only showing the average temperature does leave out some information, true.

> Me? I would prefer less screen pollution with one maximum temp sensor value.

Then you just need to remove `gpu_temp` and enable `gpu_junction_temp`.

Maybe a different solution to the space/information problem would be to have an option to combine average and junction temperature with brackets or parentheses (or some other way). For example: 60 (72ᴶⁿᶜ) °C

**Comment by flightlessmango** [comment]
Closing this as it seems generally unpopular
