### ISSUE TITLE
CrossHair

### ISSUE THREAD

**Issue by remi75** [flightlessmango/MangoHud#224]
Hello and thank you again for mangohud :)

May we know why the cross-hair feature has been removed ?

Regards

**Comment by flightlessmango** [comment]
Because it can be argued to be a cheat. My reasoning is that it would be very unfortunate if MangoHud got blacklisted as a cheat by anticheats simply on the basis of that one feature.
I think it's important to be clear with what MangoHud is and what it's used for. The crosshair feature muddies the water in that respect

**Comment by remi75** [comment]
That is your software and opinion :) 
You are giving me the occasion to fork it and re-implement it ;)
At least, I'll try .

Regards.

**Comment by flightlessmango** [comment]
I've contemplated making a separate project that adds crosshair etc, based on mangohud but doesn't have any of the other mangohud features

**Comment by Thann** [comment]
Sorry for the necrobump, but I re-added the feature on my fork =]

https://github.com/Thann/MangoHud

**Comment by spider3000** [comment]
> I've contemplated making a separate project that adds crosshair etc, based on mangohud but doesn't have any of the other mangohud features

Also apologies for the necrobump. Thanks for this amazing project. Out of curiousity, have you given this separate project more thought? Would love to see overlay tools like this in a well-maintained up-to-date project, that would be compatible with the newest Mangohud.
