### ISSUE TITLE
Mangohud shows up only when playing Dusk in windowed mode 

### ISSUE THREAD

**Issue by warriormaster12** [flightlessmango/MangoHud#238]
Dusk is made with Unity so you might be able to reproduce this bug with any Unity game that uses Opengl. 

Here are screenshots from the game:
![Screenshot_20200619_120346](https://user-images.githubusercontent.com/33091666/85115939-2f943e80-b225-11ea-9345-01604730f3c4.png)
![Screenshot_20200619_120549](https://user-images.githubusercontent.com/33091666/85115961-39b63d00-b225-11ea-87fd-c3b36812b926.png)

**Comment by ThrashMetalComputers** [comment]
I will try to replicate this when I get back home.

**Comment by aoanla** [comment]
Avoiding opening a new issue: I see the same effect in Polybius [running in Proton with Steam] and the git head build of MangoHud. 
In windowed mode, the overlay renders; in fullscreen, it doesn't. 
[Some of mangohud's OpenGL injection is still working though - Polybius needs mangohud to apply opengl vsync, and that still works, even in fullscreen.]

**Comment by svanheulen** [comment]
I have this same issue with Enter the Gungeon, which also uses Unity and is a native Linux build. It displays fine when in windowed mode but not when full screen.

And I can confirm that MangoHud is working, it just doesn't show the HUD. I enabled Steam's built-in FPS display and I could toggle MangoHud's frame limiter and see that it was working correctly.

Also I can force the game to use Unity's Vulkan backend with the `-force-vulkan` option which allows MangoHud to display correctly in full screen mode... but then the game crashes once you get past the main menu.

**Comment by jackun** [comment]
`gl_bind_framebuffer = 0` _probably_ helps.

**Comment by flightlessmango** [comment]
![image](https://github.com/flightlessmango/MangoHud/assets/42713625/61154412-6bde-41b0-b098-51120f6e2190)
works fine here without any tricks

**Comment by FLAGEL** [comment]
This issue seems to be relevant for Deus EX: GOTY Edition as well.

When launching with `mangohud %command%` via the Steam Flatpak, MangoHud is running but not shown, unless toggled in-game to windowed mode (see attached below). That in turn has other issues, as single-digit FPS and a blacked out game-window. The same behavior occurs when leaving launch options empty and enabling MangoHud via Steam Tinker Launch. Tested compatibility layers were forced to Proton Experimental and GE-Proton8-25.

It is clear  MangoHud is running in the background when full-screen as FPS limiting (and toggling via LShift + F1) works. Additionally, MangoHud keeps printing to stdout: `[2024-01-02 22:25:25.249] [MANGOHUD] [info] [gl_renderer.cpp:422] GL version: 4.6 `

![Screenshot_2024-01-02_21-51-15](https://github.com/flightlessmango/MangoHud/assets/16175171/7c91e49d-5a53-4528-9d38-5a16958d4e7a)

**Setup**
[1] com.valvesoftware.Steam 1.0.0.78, org.freedesktop.Platform.VulkanLayer.MangoHud 0.7.0
[2] Linux host 6.6.8-arch1-1 https://github.com/flightlessmango/MangoHud/pull/1 SMP PREEMPT_DYNAMIC Thu, 21 Dec 2023 19:01:01 +0000 x86_64 GNU/Linux

**Comment by xjyuzh** [comment]
> `gl_bind_framebuffer = 0` _可能_有帮助。

cool
