### ISSUE TITLE
Please allow the option to remove the graph

### ISSUE THREAD

**Issue by ale-novo** [flightlessmango/MangoHud#242]
Hi , i love MangoHud, thanks for the work
im not very interested on the graph, and its taking screen real state.
ive tried commenting both parameters:

### Display the frametime line graph
#frame_timing
# histogram

But this however still displays the frame timing graph
allow please the option to remove the graph from the screen.
thanks.

**Comment by flightlessmango** [comment]
You haft to explicitly disable it `frame_timing=0`

**Comment by Yowlen** [comment]
That seems... counter-intuitive, at best. Just let us disable them via comment hashes and scrap the requirement of having to add extra lines for options that are already there in the first place.

**Comment by Yowlen** [comment]
Why was this closed? This is a valid accessibility issue.

**Comment by jackun** [comment]
Patches welcome if you want to complicate config parsing even more

**Comment by Yowlen** [comment]
Isn't adding the `[option]=0` support the thing that's complicating the config parsing? You already have the "don't display this item unless it's explicitly enabled" support, so why not just make it universal for all options instead of having select few like `frame_timing` that use different parsings?

**Comment by jackun** [comment]
Some things are enabled by default. So you'd have to start parsing every commented line too, _maybe_ it is disabled or maybe you have bajillion temporary values like 
```#fps_limit=30
#fps_limit=60
fps_limit=144
#fps_limit=120
```
Parsing line-by-line you'd have to remember at #fps_limit=120 that fps_limit=144 was enabled. Why this crap when `frametime=0` works

**Comment by Yowlen** [comment]
Which honestly makes no sense. It makes sense to use a default group as a fallback if MangoHud can't find a config file or can't find any valid options inside the config file, but outside of that, just globally parsing the uncommented lines seems fine since the example config is already set up to represent the defaults.

Besides, what's the point of having the non-variable `frame_timing` line in the first place if it doesn't do anything without the `=0`? Even if you kept the current method, wouldn't it make more sense to have `# frame_timing=0` in there instead? At least then, the user knows that it's enabled by default and they can just comment/uncomment as necessary.

**Comment by jackun** [comment]
Hmm, looking over config parser, maybe with some rejiggling it could be made work like if no config file is parsed _then_ set defaults.

**Comment by Yowlen** [comment]
Thank you. I'm glad we could come to an understanding together. It may seem small for most, but universal config parsing, even for the defaults, is a rather big accessibility issue for some of us. Ensuring we only need one method to enable and disable the options we need/want prevents unnecessary frustration when suddenly a specific option doesn't disable/enable properly.

This app is absolutely a great app that has honestly helped me ensure my computer has adequate cooling for my more demanding games. Thank you for all the work that all of you have already put into it, and I look forward to seeing it develop even more in the future.

And lastly, my apologies if anything I said came across as hostile. It was not my intent, so if anything did, I want to make sure I correct it.

**Comment by flightlessmango** [comment]
Seems a little sketchy as suddenly everyone's MangoHud's will start looking different overnight and everyone has to edit their config files. It's gonna be a messy transition with lots of github issues

**Comment by Yowlen** [comment]
I won't deny that there will be a bit of a messy transition for some folks, but this'll really only affect two groups of people:

1. Those that removed the default stuff from their config files.
2. Those that added the `=0` config line, but left the original uncommented. (i.e. where you have both a `frame_timing` line and a `frame_timing=0` one)

The first isn't likely to happen if people use the example config as a template, which already has all the defaults uncommented and is the recommended method to use in the installer anyway, so there shouldn't be a whole lot of people that will be affected by this particular one.

The second can be solved by tweaking the config parser to prefer the legacy `=0` options if they're present.

One additional thing I thought of while writing this was how the colors, fonts, and transparency might end up looking different if the implementation is wrong due to them being commented out by default, but as long as the checks after the config file is read are done on a per-variable basis instead of just a global "did the config file set stuff" basis, it's easy to set those to the defaults afterwards.

All in all, it can be done so that only those that actually removed the uncommented defaults without adding the `=0` equivalent will be affected by the change. And that won't be too hard to notify people about.

**Comment by flightlessmango** [comment]
A third group of people would be those who use Goverlay, depending on  how that's written we might bork the current release

heads up @benjamimgois
