### ISSUE TITLE
[Feature Request] Add more advanced commands for customization

### ISSUE THREAD

**Issue by fagnerln** [flightlessmango/MangoHud#244]
One of the best things of MangoHud is the simplicity, it's easy to understand the configuration and how to enable/disable features. But with this simplicity makes the customization a bit limited.

Would be nice if alternatively we can configure it like Conky, so the user can add whatever he want, like cpu clock, individual core usage, the use of bars instead of numbers, net utilization, the day of the month (?), etc...

I miss some commands (based on what conky have) like:
${execi} and ${execibar} which grabs anything that we can get on terminal
${alignr} and ${alignc} to align individual values on the box
${font} to define the font of that specific line
${color} to define the color of the line
${hr} do make a horizontal line separating the lines
${voffset} to mess with the lines

Maybe there's a better way to do this without messing with the structure of the MangoHud, but it's just an example. Thanks

**Comment by flightlessmango** [comment]
This would require a major overhaul of the ui, The first step we need to take is making it so user can choose the order that the lines comes in. But we have not found a way to do that yet.

I'm also concerned about performance. Since this is a benchmarking tool, I don't like the idea of users modifying it to the extent where loss of performance may occur

**Comment by fagnerln** [comment]
Maybe when it start recording the benchmark, just stops what it isn't using, and I think that if the interval is >1s isn't that resource heavy. 

Like as I said it's already good enough, if it really need a big change in the UI, rewriting it, feel free to close as resolved.
