### ISSUE TITLE
Configuration unclear

### ISSUE THREAD

**Issue by X6205** [flightlessmango/MangoHud#260]
Hi,

Since new version 0.4.1 there are som unclear changes in configuration, can you please clarify it for me? Because example conf. file from /doc does not reflect these changes.

1./ driver info was missing, but adding vulkan_driver to .conf file had enabled this feature again, but some things are still missing, but nothing important

2./ no matter what i do, when i enable GPU clock, it is pushed to second row instead of addind third column like in v0.3.5.1
![v0 4 1](https://user-images.githubusercontent.com/14248415/85921114-f8074100-b879-11ea-9ba0-ba3cf3991da7.png)

3./ parameter "gpu_stats" in conf file will hide everything GPU related. Is this behaviou OK? Because if i want to see only gpu_temp and gpu_core_clock, disabling gpu_stats will disable everything. I was asuming it will hide only gpu load in percentage

**Comment by flightlessmango** [comment]
1. Yes driver information is under the vulkan_driver param now, it was never meant to be enabled by default. What other things are missing and are they not in the list on the readme?

2. We decided to have it this way since it was easier code wise

3. gpu_stats toggles all gpu stats. A gpu_load param could be added to toggle the gpu load

**Comment by X6205** [comment]
What do you mean by gpu_load? I have tried this param but it looks like its doing nothing.

**Comment by flightlessmango** [comment]
I'm saying that something like that could be added, it would be a new feature

**Comment by X6205** [comment]
Oh.. i understand. Maybe one day :) Thanks for explanation.
