### ISSUE TITLE
How can I use it in Teeworlds?

### ISSUE THREAD

**Issue by Toadfield** [flightlessmango/MangoHud#393]
It doesn't work in Teeworld with this Launch options: `MANGOHUD=1 MANGOHUD_DLSYM=1  mangohud %command%`
I don't know what api that game uses.
I use the steam version.

**Comment by Leopard1907** [comment]
`mangohud` works for both Vulkan (native Vulkan, DXVK [DX9 , 10 ,11 ] , VKD3D [DX12] and OpenGL ( wined3d , native OGL)

`mangohud --dlsym` is a valid launch option as well.

You seem to spam this tracker a lot. Instead of doing it you can read the readme when you have an issue of remembering commands,env vars.

For the api's games are using , you can check pcgamingwiki for each individual game.

**Comment by Toadfield** [comment]
> mangohud --dlsym is a valid launch option as well.

That still doesn't work.

> For the api's games are using , you can check pcgamingwiki for each individual game.

The api of that game isn't listed there.

**Comment by flightlessmango** [comment]
These kinds of questions would be better directed to the discord server, github issues are more for bugs and issues with mangohud itself

That being said, it works just fine on my end with steam version `mangohud %command%` or downloaded from the arch community repo `mangohud teeworlds`
