### ISSUE TITLE
How to get it to work with a Wine game running from Lutris

### ISSUE THREAD

**Issue by plazia** [flightlessmango/MangoHud#514]
A lot of people on here and on youtube have mentioned how to get it to work with wine games or with Lutris. Fair enough. I play Wrath of the Lich King (Wow 3.3.5) on Warmane a private server. I have my game launched with Lutris, Everything works fine but I have no idea how to get mango hud to display. I can get it to display with Steam games such as Vahleim though.

I've tried going to env variables and making MANGOHUD and 1 in the next column. That doesn't work.

Could anyone point me to where I'm going wrong here? 

Fantastic bit of software btw. (Mangohud)

**Comment by baryluk** [comment]
I don't play many games using lutris, but I right click on a game -> Configure -> System options -> Command prefix: `env mangohud`. If needed adjust `MANGOHUD_CONFIG=...` either by puting it between `env` and `mangohud` elements of "command prefix", or in "Environment variables" on the same tab in Configure in lutris.

Works for me just fine.

Sometimes you need to use `mangohud --dlsym` instead of mangohud.

Also make sure you have both 64-bit and 32-bit libraries installed for mangohud. I think the `build.sh` does this automatically but in many distros you have two install separate pacakges, i.e. on Debian testing you need `mangohud:amd64 mangohud:i386` packages, they are coinstallable, and the `mangohud` script is the same and will automatically select proper version of mangohud for each program.

**Comment by plazia** [comment]
Thanks ever so much baryluk. The last paragraph you posted turned out to be the solution. I simply installed the lib32-mangohud from the AUR (Arch BTW) and that resulted in MangoHUD showing up instantly upon restarting the game. Thanks ever so much for the reply and solution.
