### ISSUE TITLE
Can Mangohud show ping?

### ISSUE THREAD

**Issue by Cicango** [flightlessmango/MangoHud#537]

**Comment by flightlessmango** [comment]
It can't and I don't think it's feasible

**Comment by Faalagorn** [comment]
I saw that discussion in Discord, so will repond here as well in case anyone finds it.

Technically, it can be achieved with `exec`, here's an example:

it can be achieved with exec command now if you know which server to ping, example from this one: https://unix.stackexchange.com/questions/409203/ping-show-only-results

```
custom_text=Ping
exec=ping -qc1 1.1.1.1 2>&1 | awk -F'/' 'END{ print (/^rtt/? ""$5" ms":"FAIL") }
```

MangoHud will query each time FPS is refreshed by `fps_sampling_period`  (default 500ms). Probably with some clever scripting, you can extract running server's IP you're playing it and input the result to the `exec` instead of hardcoding it.
