### ISSUE TITLE
what options can be changed on the fly?

### ISSUE THREAD

**Issue by kokoko3k** [flightlessmango/MangoHud#71]
By using the handy reload config option, I just tried to change vsync method and fps limits in the config file and hit F4, but it seems to just ignore me.
The log seems fine:
``` parsing config: /home/koko/.config/MangoHud/MangoHud.conf [ ok ] ```
are them supposed to work, and if not maybe can you consider it? thanks!

**Comment by flightlessmango** [comment]
Most options should work, note that options like `frame_timing` needs to explicitly be set to off `frame_timing = 0`. This should be fixed in the develop branch. `fps_limit` does not work currently, but should be very doable, I'll put it on my todo list. Vsync however I don't think is possible to change while running
