### ISSUE TITLE
Wine and Steam do not run games and programmes

### ISSUE THREAD

**Issue by guglovich** [flightlessmango/MangoHud#733]
There's been a long issue with Steam not starting games + the descendant processes not closing, as well as Steam itself. I did a lot of digging into the problem and noticed that Wine is also broken. Checking the package removal method I got to MangoHud and it turned out to be the cause of the problem. However, as I understand it is a problem only when installing from AUR regular version of mangohud if user has AMD video card. I uninstalled this version, killed all the Wine descendant processes and installed the mangohud-nonvidia version and everything works. 

So please, if anyone has Arch + AMD Radeon, check this package and then either fix the problem or specify on the main page that users with Radeon need to install mangohud-nonvidia version.

**Comment by flightlessmango** [comment]
try `mangohud-git` to check that this hasn't already been fixed

**Comment by guglovich** [comment]
> try `mangohud-git` to check that this hasn't already been fixed

The git has been fixed. So you should temporarily remove the link to the regular version from the home page or write a warning. Because not everyone knows this bug and Steam github already has reports with a non-working app. I duplicated the information there, but not everyone goes to github.

**Comment by Axvalor** [comment]
`try mangohud-git to check that this hasn't already been fixed`
Thanks! This also fixed it for me.
`as I understand it is a problem only when installing from AUR regular version of mangohud if user has AMD video card.`
I can confirm that it also happens with Nvidia cards, at least in my case. Another of the symptons that was fixed by updating MangoHud was that Lutris would not start unless I explicitly disabled MangoHud (I have `export MANGOHUD=1` on my `~/.profile`) as discussed in lutris/lutris#3720. I think that installing `mangohud-nonvidia` can fix the issue for AMD users because it was updated on 2022-03-18, while `mangohud` was last updated on 2021-10-26.

**Comment by guglovich** [comment]
Now I can't run games with any of the three versions.

**Comment by flightlessmango** [comment]
What mangohud version was used? (not if it's `-git` or `nonvidia`, but the actual git hash)
Does mangohud work with vkcube?
Can you provide a steam log file from when a game failed to start?

**Comment by guglovich** [comment]
@flightlessmango mangohud-common 0.6.7.1, mangohud-nonvidia-0.6.7, git - last
works with vkcube
maybe there was a problem with wine-staging 7.7, with 7.8 it ran without problems. or another problem. now it works with mangohud-common
Steam games on the new versions were already without problems, a few times it was the former Wine that had problems.
