### ISSUE TITLE
Zink detection don't work

### ISSUE THREAD

**Issue by Francehelder** [flightlessmango/MangoHud#750]
I'm using Endeavour OS with the last mangohud version e Zink detection don't work

**Comment by logan001** [comment]
mangohud 0.6.7 with steam and zink mangohud amd APU now shows OpenGL. previous version (i think 0.6.6) showed Zink.
i can tell zink works while mangohud shows OpenGL because of the bugs in rendering.

but i have to mention that last time i've tried mangohud was 2 months ago i think. so maybe is something related to zink or to mangohud or both :)

**Comment by flightlessmango** [comment]
should be fixed here 3e57824f001e8ecb8c1fe7dce6bb44a1c706063e

**Comment by logan001** [comment]
recompile it from aur and now it works.
