### ISSUE TITLE
Running MangoHud with proton games results in sh: 1: glxinfo: not found

### ISSUE THREAD

**Issue by hashworks** [flightlessmango/MangoHud#840]
Running MangoHud with proton games results in the following console error: `sh: 1: glxinfo: not found`. This isn't the case with native games, `glxgears` is in `$PATH`.

This seems to be a minor issue - I haven't found any issues with MangoHud or the information it displays:
![img-2022-09-27-162602](https://user-images.githubusercontent.com/2362091/192554345-43933b23-3af8-463f-931e-50fe75c0ea58.png)

I'm using the latest [`mangohud` AUR PKGBUILD](https://aur.archlinux.org/packages/mangohud) (0.6.8-2) on Arch Linux.

**Comment by flightlessmango** [comment]
This used to be the way we fetched GPU name, I think we rely on different methods now and this should be removed from the code

**Comment by flightlessmango** [comment]
glxinfo is no longer used

**Comment by HydeFromT70s** [comment]
> glxinfo is no longer used

Are you sure about this? Because when I try to run any proton game via steam using mangohud I simply can't. I'm getting this error about missing glxinfo:

`[2023-06-19 21:54:22.640] [MANGOHUD] [info] [config.cpp:118] skipping config: '/home/<user>/.config/MangoHud/wine-explorer.conf' [ not found ]
[2023-06-19 21:54:22.640] [MANGOHUD] [info] [config.cpp:118] skipping config: '/mnt/Dane/Gry/steamapps/common/Proton - Experimental/files/bin/MangoHud.conf' [ not found ]
[2023-06-19 21:54:22.640] [MANGOHUD] [info] [config.cpp:118] skipping config: '/home/<user>/.config/MangoHud/wine64-preloader.conf' [ not found ]
[2023-06-19 21:54:22.640] [MANGOHUD] [info] [config.cpp:123] parsing config: '/home/<user>/.config/MangoHud/MangoHud.conf'
sh: 1: glxinfo: not found
`
glxinfo is located in `/usr/bin/glxinfo`

When I uninstall mangohud steam runs proton games without any issue. I'm not a programmer but it clearly points an issue with mangohud.

MangoHud 0.6.9.1-8

**Comment by flightlessmango** [comment]
Yes I'm certain about that ea3ba7e
This error never did anything, it was just log spam.
Your issue is probably more like #1014
