### ISSUE TITLE
Paypal link in data/io.github.flightlessmango.mangohud.metainfo.xml causes Arch pkgbuild to fail when paypal is not allowed

### ISSUE THREAD

**Issue by ap4ss3rby** [flightlessmango/MangoHud#928]
I cannot connect is to paypal.me (gives me error 403), and I don't need it where I live, and I mostly ignore its existence... until I try to build mangohud. For now working around the paypal error either involves building with a VPN active or commenting out the offending paypal link from the source then running building again without resyncing sources.

**Comment by flightlessmango** [comment]
I don't understand how that would have any effect on the build process

**Comment by ap4ss3rby** [comment]
Copying directly from the makepkg's output without modifying the source


==> Starting check()...
W: io.github.flightlessmango.mangohud:30: url-not-reachable
     https://www.paypal.me/flightlessmango - Unexpected status code: 403

✘ Validation failed: warnings: 1
==> ERROR: A failure occurred in check().
    Aborting...

**Comment by flightlessmango** [comment]
And you post the full log please?

**Comment by gort818** [comment]
I am assuming this is from the aur, not really our issue.

comment this out in the pkgbuild 
```
check() {
  cd "$srcdir/MangoHud"
  appstreamcli validate --pedantic "data/io.github.flightlessmango.$pkgbase.metainfo.xml"
}
```

**Comment by ap4ss3rby** [comment]
[buildlog.log](https://github.com/flightlessmango/MangoHud/files/10760949/buildlog.log)

I was building with paru, then I had this error. Deleting the donation link (under src/Mangohud/data/io.github.flightlessmango.mangohud.metainfo.xml) allows check() in the PKGBUILD to work fine.

**Comment by flightlessmango** [comment]
I don't think it makes sense for us to remove valid links because you have issues reaching them.
Few solutions I would suggest.
- modify hosts so paypal.me goes to google.com (or any reachable host)
- make an issue on appstream to include an option to validate without checking urls
- ask the aur package maintainer not to include the check()

**Comment by jn64** [comment]
> make an issue on appstream to include an option to validate without checking urls

This is already possible. @ap4ss3rby you can use `appstreamcli validate --no-net`, instead of removing the check entirely or editing the xml file.

Most distros with sane packaging policies disallow network access during builds. AUR has no such provision, but you might want to suggest this change to your package maintainers since it'll be useful for others in a similar situation.

**Comment by eclairevoyant** [comment]
@jn64 fyi AUR packages are maintained by random users, not official Arch maintainers, so anyone can upload content even if it doesn't follow policies. Anyway, thanks for the info

**Comment by jn64** [comment]
Thanks for following up with the maintainer. [Downstream has made the suggested change](https://aur.archlinux.org/cgit/aur.git/commit/PKGBUILD?h=mangohud&id=231d97c1fa40fd02b3d680919e34b31121b1d10b) so issue can be closed (should've been closed anyway).
